version: '3.8'

services:
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@db:5432/line_bot_db  #     - DJANGO_SETTINGS_MODULE=line_bot_project.settings
  #   depends_on:
  #     - db
  #   networks:
  #     - line-bot-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=line_bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - line-bot-network

volumes:
  postgres_data:

networks:
  line-bot-network:
    driver: bridge