version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/line_bot_db 
      - DJANGO_SETTINGS_MODULE=line_bot_project.settings
    depends_on:
      - db
    networks:
      - line-bot-network

  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok
    command: ngrok http web:8000 --authtoken ${NGROK_AUTH_TOKEN}  # 直接在命令中使用 authtoken
    ports:
      - "4040:4040"
    depends_on:
      - web
    networks:
      - line-bot-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=line_bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - line-bot-network

volumes:
  postgres_data:

networks:
  line-bot-network:
    driver: bridge