# Generated by Django 5.1.2 on 2024-10-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('tag_name', models.CharField(max_length=100)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(default=dict, blank=True)),
            ],
            options={
                'db_table': 'user_tags',
            },
        ),
    ]
